apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-prod
  namespace: demo-namespace-prod
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    canary:
      canary:
        percent: 10
        step: 10
        start_step: 0
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      automountServiceAccountToken: true
      containers:
        - name: frontend
          image: europe-west9-docker.pkg.dev/incubation-ids/demo-gke-repo/angular:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 350m
              ephemeral-storage: 1Gi
              memory: 512Mi
            requests:
              cpu: 350m
              ephemeral-storage: 1Gi
              memory: 512Mi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
      enableServiceLinks: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: cloud-sql-access
      serviceAccountName: cloud-sql-access
      shareProcessNamespace: false
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloud-sql-instance-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-prod
  namespace: demo-namespace-prod
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.227.3
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend
  sessionAffinity: None
  type: LoadBalancer
