apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-prod-stable
  namespace: demo-namespace-prod
  labels:
    app: frontend
    version: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: stable
  template:
    metadata:
      labels:
        app: frontend
        version: stable
    spec:
      containers:
      - name: frontend
        image: europe-west9-docker.pkg.dev/incubation-ids/demo-gke-repo/angular:latest
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_IP
          valueFrom:
            secretKeyRef:
              key: BACKEND_IP
              name: backend-ip
              optional: false
        - name: ENV
          value: "PROD"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-stable
  namespace: demo-namespace-prod
  labels:
    app: frontend
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: frontend
    version: stable

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-prod-canary
  namespace: demo-namespace-prod
  labels:
    app: frontend
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: canary
  template:
    metadata:
      labels:
        app: frontend
        version: canary
    spec:
      containers:
      - name: frontend
        image: europe-west9-docker.pkg.dev/incubation-ids/demo-gke-repo/angular:latest
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_IP
          valueFrom:
            secretKeyRef:
              key: BACKEND_IP
              name: backend-ip
              optional: false
        - name: ENV
          value: "PROD"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-canary
  namespace: demo-namespace-prod
  labels:
    app: frontend
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: frontend
    version: canary

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-vs
  namespace: demo-namespace-prod
spec:
  hosts:
  - frontend.demo-namespace-prod.svc.cluster.local
  http:
  - match:
      - uri:
          prefix: /
    route:
    - destination:
        subset: canary
        port:
          number: 80
      weight: 50  # 50% of traffic to canary
    - destination:
        subset: stable
        port:
          number: 80
      weight: 50  # 50% of traffic to stable

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend-dr
  namespace: demo-namespace-prod
spec:
  host: frontend.demo-namespace-prod.svc.cluster.local
  subsets:
  - name: canary
    labels:
      version: canary
  - name: stable
    labels:
      version: stable

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: frontend-gateway
  namespace: demo-namespace-prod
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP


---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-vs
  namespace: demo-namespace-prod
spec:
  hosts:
  - frontend.demo-namespace-prod.svc.cluster.local
  http:
  - match:
      - uri:
          prefix: /
    route:
    - destination:
        host: frontend.demo-namespace-prod.svc.cluster.local
        subset: canary
        port:
          number: 80
      weight: 50
    - destination:
        host: frontend.demo-namespace-prod.svc.cluster.local
        subset: stable
        port:
          number: 80
      weight: 50
