apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-prod-stable
  namespace: demo-namespace-prod
  labels:
    app: frontend
    version: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: stable
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: frontend
        version: stable
    spec:
      containers:
      - name: frontend
        image: europe-west9-docker.pkg.dev/incubation-ids/demo-gke-repo/angular:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-prod-stable
  namespace: demo-namespace-prod
spec:
  selector:
    app: frontend
    version: stable
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
