# Delivery Pipeline for Backend
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: fastapi-delivery-pipeline
  description: Main application pipeline for FastAPI
serialPipeline:
  stages:
    - targetId: fastapi-deployment
      profiles: 
        - dev
    - targetId: fastapi-deployment-prod
      profiles: 
        - prod
      strategy:
        canary:
          runtimeConfig:
            kubernetes:
              serviceNetworking:
                service: "backend-prod-stable"
                deployment: "backend-prod-stable"
          canaryDeployment:
            percentages: [50]
            verify: false

---

# Development Target for Backend
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: fastapi-deployment
  description: Development cluster for FastAPI
gke:
  cluster: projects/incubation-ids/locations/europe-west1/clusters/demo-cluster-1

---

# Production Target for Backend
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: fastapi-deployment-prod
  description: Production cluster for FastAPI
requireApproval: true
gke:
  cluster: projects/incubation-ids/locations/europe-west1/clusters/demo-cluster-1
