apiVersion: skaffold/v4beta7
kind: Config
profiles:
  - name: prod
    manifests:
      rawYaml:
        - kubernetes/manifest-prod.yaml
  - name: dev
    manifests:
      rawYaml: 
        - kubernetes/manifest-dev.yaml