# clouddeploy.yaml
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: angular-delivery-pipeline
  description: main application pipeline
serialPipeline:
  stages:
    - targetId: angular-deployment
      profiles: 
        - dev
    - targetId: angular-deployment-prod
      profiles: 
        - prod
      strategy:
        canary:
          runtimeConfig:
            kubernetes:
              serviceNetworking:
                service: "frontend"
                deployment: "frontend-prod-stable"
          canaryDeployment:
            percentages: [50]
            verify: false
