# clouddeploy.yaml
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: angular-delivery-pipeline
  description: main application pipeline
serialPipeline:
  stages:
    - targetId: angular-deployment
      profiles: 
        - dev
    - targetId: angular-deployment-prod
      profiles: 
        - prod
      strategy:
        canary:
          runtimeConfig:
            kubernetes:
              serviceNetworking:
                service: "frontend"
                deployment: "frontend-prod-stable"
          canaryDeployment:
            percentages: [50]
            verify: false
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-vs
  namespace: demo-namespace-prod
spec:
  hosts:
  - frontend.demo-namespace-prod.svc.cluster.local
  http:
  - match:
      - uri:
          prefix: /
    route:
    - destination:
        host: frontend.demo-namespace-prod.svc.cluster.local
        subset: canary
        port:
          number: 80
      weight: 50
    - destination:
        host: frontend.demo-namespace-prod.svc.cluster.local
        subset: stable
        port:
          number: 80
      weight: 50

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend-dr
  namespace: demo-namespace-prod
spec:
  host: frontend.demo-namespace-prod.svc.cluster.local
  subsets:
  - name: canary
    labels:
      version: canary
  - name: stable
    labels:
      version: stable