steps:
# if the docker file is not in the same location then give a full path otherwise use “.”
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t','europe-west9-docker.pkg.dev/incubation-ids/demo-gke-repo/angular:latest', 'angular/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west9-docker.pkg.dev/incubation-ids/demo-gke-repo/angular:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - >
    gcloud deploy apply --file=clouddeploy.yaml --region=europe-west9 --project=incubation-ids
  args:
  - '-c'
  - >
   
    # release--$SHORT_SHA
    gcloud deploy releases create release-shubhi1 --delivery-pipeline=shubhi-pl --region=europe-west9 --source=./ --images=europe-west9-docker.pkg.dev/incubation-ids/demo-gke-repo/angular:latest=europe-west9-docker.pkg.dev/incubation-ids/demo-gke-repo/angular:latest --project=incubation-ids