# clouddeploy.yaml
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: angular-delivery-pipeline
  description: Main application pipeline
serialPipeline:
  stages:
    - targetId: angular-deployment
      profiles: 
        - dev
    - targetId: angular-deployment-prod
      profiles: 
        - prod
      strategy:
        canary:
          runtimeConfig:
            kubernetes:
              serviceNetworking:
                service: "frontend-stable"  # Reference the stable service
                deployment: "frontend-prod-stable"
          canaryDeployment:
            percentages: [50]  # Adjust this percentage as needed
            verify: false  # Set to 'true' if you want to add automated verification steps
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: angular-deployment
description: Development namespace
gke:
  cluster: projects/incubation-ids/locations/europe-west1/clusters/demo-cluster-1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: angular-deployment-prod
description: Production
requireApproval: true  # Set to 'true' if you want to require manual approval before deploying to production
gke:
  cluster: projects/incubation-ids/locations/europe-west1/clusters/demo-cluster-1

