#clouddeploy.yaml
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: angular-delivery-pipeline
  description: main application pipeline
serialPipeline:
  stages:
    - targetId: angular-deployment
    - targetId: angular-deployment-prod
      strategy:
        canary:
          customCanaryDeployment:
            phaseConfigs:
              - phaseId: canary-25
                percentage: 25
                verify: true
              - phaseId: canary-50
                percentage: 50
                verify: true
              - phaseId: canary-75
                percentage: 75
                verify: true
              - phaseId: stable
                percentage: 100
                verify: true
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: angular-deployment
  description: development namespace
gke:
  cluster: projects/incubation-ids/locations/europe-west1/clusters/demo-cluster-1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: angular-deployment-prod
  description: production
gke:
  cluster: projects/incubation-ids/locations/europe-west1/clusters/demo-cluster-1

       
